### PR TITLE
v1.0.2 - upgrade dependencies for CVE & docker improvements

### PR DESCRIPTION
**Pull request by chrroberts-pure**
Per the Quay.io image analyzer there was a number of CVEs that affected the 1.0.1 image. 
The dependencies have been upgraded as required.

This 1.0.2 version also includes the image enhancements that reduce the size of the image.

### CODE REVIEW

**Review by sdodsley — APPROVED** [review]

**Comment by chrroberts-pure** [comment]
@genegr can you please review this? Thanks.

**Review by genegr — CHANGES_REQUESTED** [review]
All the changes look good to me, but before bumping the new release we should add a small change to the Makefile in order to let the compiler automatically include the code version at line 27, like this:

`CGO_ENABLED=0 GO111MODULE=on $(GOCMD) build -a -tags 'netgo osusergo static_build' -ldflags='-X main.version=v$(VERSION)' -o out/bin/$(BINARY_NAME) cmd/fb-om-exporter/main.go`

and replace line 17 of cmd/fb-om-exporter/main.go with this

`var version string = "development"`

**Comment by chrroberts-pure** [comment]
@genegr check this out - the makefile version should be the only version now. I also implemented version as a build-arg in the dockerfile as well.

**Review by sdodsley — APPROVED** [review]
Looks OK to me.

**Pull request merged**
